// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Copyrights: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/Copyrights.vue')['default'];
    CTA: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/CTA.vue')['default'];
    Demos: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/Demos.vue')['default'];
    DesktopMenu: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/nav/DesktopMenu.vue')['default'];
    Features: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/Features.vue')['default'];
    Hero: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/Hero.vue')['default'];
    ICarbonAccessibility: typeof import('virtual:vite-icons/carbon/accessibility')['default'];
    IMdiAccountBox: typeof import('virtual:vite-icons/mdi/account-box')['default'];
    ITeenyiconsCss3Outline: typeof import('virtual:vite-icons/teenyicons/css3-outline')['default'];
    Logo: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/Logo.vue')['default'];
    LogoCloud: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/LogoCloud.vue')['default'];
    LogoLink: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/LogoLink.vue')['default'];
    LogoMini: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/LogoMini.vue')['default'];
    MailCTA: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/MailCTA.vue')['default'];
    MainNav: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/nav/MainNav.vue')['default'];
    Separator: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/Separator.vue')['default'];
    SeparatorTwo: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/SeparatorTwo.vue')['default'];
    SiteMap: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/SiteMap.vue')['default'];
    Socials: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/Socials.vue')['default'];
    Stats: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/home/Stats.vue')['default'];
    TheFooter: typeof import('C:/Users/arbus/Documents/Gatobuho/gatobuho/src/components/TheFooter.vue')['default'];
  }
}

export {};
